import { Code2 } from 'lucide-react';
import { useDevtoolsStore } from '../stores/devtoolsStore';

/* ═══════════════════════════════════════════════════════════════════
   ShadersTab — Shader 变体检查器（占位实现）
   MVP 阶段仅显示提示文字 + 选中变体名称。
   后续集成引擎后增加：变体列表、WGSL 代码高亮、编译信息等。
   ═══════════════════════════════════════════════════════════════════ */

/** Lucide 图标尺寸（像素） */
const ICON_SIZE = 32;

/**
 * Shader 变体检查器 Tab（占位实现）。
 *
 * 当前功能：
 * - 无选中变体时显示提示文字
 * - 有选中变体时显示变体名称
 *
 * 后续集成引擎后增加：
 * - 左侧面板：Shader 变体列表（ShaderVariantKey），标记 "Used in last frame"
 * - 右侧面板：选中变体的汇编后 WGSL 代码（Vertex + Fragment 两个代码块）
 * - Shiki WGSL 语法高亮
 * - 编译耗时、Pipeline 状态等元信息
 *
 * @returns Shader Tab JSX
 *
 * @example
 * <ShadersTab />
 */
export function ShadersTab() {
  /* 从 store 获取当前选中的 Shader 变体标识 */
  const selectedShaderVariant = useDevtoolsStore((s) => s.selectedShaderVariant);

  return (
    <div className="flex h-full flex-col overflow-y-auto p-3">
      {selectedShaderVariant ? (
        /* 有选中变体时显示变体信息 */
        <div className="flex flex-col gap-3">
          {/* 变体名称标题 */}
          <div className="flex items-center gap-2">
            <Code2 size={16} className="shrink-0 text-[var(--accent)]" />
            <span className="font-mono text-sm font-semibold text-[var(--text-primary)]">
              {selectedShaderVariant}
            </span>
          </div>

          {/* WGSL 代码占位区域 */}
          <div className="rounded-md bg-[var(--bg-input)] p-3">
            <p className="text-xs text-[var(--text-muted)]">
              WGSL source will be displayed here when the engine is connected.
            </p>
            {/* 模拟代码块外观 */}
            <pre className="mt-2 font-mono text-xs leading-relaxed text-[var(--text-secondary)]">
{`// Vertex Shader
@vertex
fn vs_main(@builtin(vertex_index) idx: u32) -> @builtin(position) vec4f {
  // ... assembled from modules
  return vec4f(0.0);
}

// Fragment Shader
@fragment
fn fs_main() -> @location(0) vec4f {
  // ... assembled from modules
  return vec4f(1.0);
}`}
            </pre>
          </div>
        </div>
      ) : (
        /* 无选中变体时显示居中占位提示 */
        <div className="flex flex-1 flex-col items-center justify-center gap-3">
          <Code2
            size={ICON_SIZE}
            className="text-[var(--text-muted)]"
          />
          <p className="text-sm text-[var(--text-muted)]">
            Shader variants will appear here during rendering
          </p>
          <p className="text-xs text-[var(--text-muted)]">
            Variants are generated by ShaderAssembler from projection, geometry, and style modules
          </p>
        </div>
      )}
    </div>
  );
}
