/**
 * Shared TypeScript types for the GIS-Forge Web GIS application (QGIS / ArcGIS Online–style UX).
 * All exports are `export type` for compatibility with `verbatimModuleSyntax: true`.
 */

/**
 * Layer kinds supported by the map style and layer tree (vector paint families + raster/3D).
 */
export type LayerKind =
  | 'fill'
  | 'line'
  | 'circle'
  | 'symbol'
  | 'raster'
  | 'extrusion'
  | 'heatmap'
  | '3d-tiles';

/**
 * GeoJSON-like geometry container used for features and annotations (coordinates are CRS-dependent).
 */
export type GeoJsonGeometry = {
  /** Geometry type string (e.g. `"Point"`, `"LineString"`, `"Polygon"`). */
  type: string;
  /** Coordinate payload; structure depends on `type` (nested arrays for rings/lines). */
  coordinates: any;
};

/**
 * Configuration for a single map layer (style, visibility, zoom range, and load/error state).
 */
export type LayerConfig = {
  /** Stable unique identifier for this layer within the map document. */
  id: string;
  /** Human-readable display name shown in the layer tree and legends. */
  name: string;
  /** Layer renderer / data family; drives available paint/layout properties and shaders. */
  type: LayerKind;
  /** Identifier of the bound data source (`SourceConfig.id`); must exist when the layer is active. */
  sourceId: string;
  /** When false, the layer is hidden but remains in the document (no rendering, may skip loading). */
  visible: boolean;
  /** Opacity multiplier for the layer composite; unitless, range 0 (fully transparent) to 1 (opaque). */
  opacity: number;
  /** Paint properties keyed by style spec names (e.g. fill color, line width); values are engine-specific. */
  paint: Record<string, any>;
  /** Layout properties (e.g. symbol placement, text fields); values are engine-specific. */
  layout: Record<string, any>;
  /** Optional Mapbox/GeoJSON-style filter expression; empty array means no filter. */
  filter: any[];
  /** Minimum zoom level (inclusive) at which the layer is evaluated; range 0–24 (OSM-style zoom). */
  minzoom: number;
  /** Maximum zoom level (inclusive) at which the layer is evaluated; range 0–24 (OSM-style zoom). */
  maxzoom: number;
  /** Last error message for layer/source binding or style compile; null when healthy. */
  error: string | null;
  /** True while tiles/features for this layer are being fetched or processed. */
  loading: boolean;
};

/**
 * Grouping node in the layer tree (basemap vs thematic vs overlays vs analysis outputs).
 */
export type LayerGroupType = 'basemap' | 'vector' | 'overlay' | 'analysis';

/**
 * A folder-like group containing ordered layers, with optional mutual exclusivity (basemap radio).
 */
export type LayerGroup = {
  /** Stable unique identifier for this group within the map document. */
  id: string;
  /** Human-readable group title shown in the layer panel. */
  name: string;
  /** Semantic group kind; basemap groups may use `exclusive` for radio selection. */
  type: LayerGroupType;
  /** Child layers in display order (often bottom-to-top within the group). */
  layers: LayerConfig[];
  /** When true, the group is collapsed in the UI; layer visibility is unaffected. */
  collapsed: boolean;
  /** When true, only one child layer may be fully “selected” at a time (typical for basemap). */
  exclusive: boolean;
};

/**
 * Remote or inline data source types (tiles, OGC, vectors, 3D Tiles).
 */
export type SourceKind =
  | 'vector-tile'
  | 'raster-tile'
  | 'geojson'
  | '3d-tiles'
  | 'wms'
  | 'wmts'
  | 'wfs'
  | 'pmtiles';

/**
 * Connection to geospatial data (URL template, inline GeoJSON, attribution, and status).
 */
export type SourceConfig = {
  /** Stable unique identifier referenced by `LayerConfig.sourceId`. */
  id: string;
  /** Source driver / protocol; determines how `url` and `data` are interpreted. */
  type: SourceKind;
  /** Primary endpoint or template URL (empty string when using inline `data` only). */
  url: string;
  /** Inline GeoJSON or engine-specific payload when not loading from `url`. */
  data: any;
  /** Attribution HTML or plain text for the attribution bar (licensing / source credit). */
  attribution: string;
  /** True while network or decode work is in progress for this source. */
  loading: boolean;
  /** Last load/parse error message; null when the source is healthy. */
  error: string | null;
};

/**
 * A vector feature as returned by identify, selection, or query (map document context included).
 */
export type Feature = {
  /** Feature identifier from data or generated by the engine; string or number per source. */
  id: string | number;
  /** Always `"Feature"` for GeoJSON feature objects. */
  type: 'Feature';
  /** Geometry in the map’s working CRS (often EPSG:4326 for GeoJSON). */
  geometry: GeoJsonGeometry;
  /** Non-geometric attributes from the dataset (fields vary by layer). */
  properties: Record<string, any>;
  /** Layer that this feature was picked from (`LayerConfig.id`). */
  layerId: string;
  /** Source backing the layer (`SourceConfig.id`). */
  sourceId: string;
};

/**
 * Saved camera bookmark (extent, mode, and layer visibility snapshot).
 */
export type Bookmark = {
  /** Unique bookmark id for edit/delete/reorder in the UI. */
  id: string;
  /** User-facing bookmark label. */
  name: string;
  /** Map center as `[longitude, latitude]` in degrees; WGS84 unless the app states otherwise. */
  center: [number, number];
  /** Zoom level; unitless OSM-like zoom, typically bounded by the engine min/max zoom. */
  zoom: number;
  /** Map rotation about the vertical axis in radians; 0 = north up (see project “bearing” convention). */
  bearing: number;
  /** Camera tilt in radians; 0 = looking straight down (2D); higher values tilt toward the horizon (3D/globe). */
  pitch: number;
  /** Layer ids that should be visible when this bookmark is applied (subset or full list). */
  visibleLayers: string[];
  /** View mode to restore: flat map, 2.5D, or globe. */
  mode: '2d' | '25d' | 'globe';
  /** Creation time as Unix milliseconds since epoch (UTC). */
  createdAt: number;
};

/**
 * User or analysis overlay geometry with label and styling (drawings, measurements).
 */
export type Annotation = {
  /** Unique id for this annotation in the document. */
  id: string;
  /** Kind of annotation or measurement tool that produced this geometry. */
  type:
    | 'point'
    | 'line'
    | 'polygon'
    | 'measure-distance'
    | 'measure-area'
    | 'measure-profile';
  /** Geometry to render and persist (structure follows GeoJSON conventions). */
  geometry: GeoJsonGeometry;
  /** Short text shown next to or in a callout for the shape. */
  label: string;
  /** Stroke/fill styling for rendering and export. */
  style: {
    /** CSS color string or engine token (e.g. `#3388ff`); applies to stroke or fill as appropriate. */
    color: string;
    /** Stroke width in CSS pixels or world units depending on renderer; omit for default width. */
    width?: number;
    /** Opacity in 0–1; omit for fully opaque where applicable. */
    opacity?: number;
  };
  /** Creation time as Unix milliseconds since epoch (UTC). */
  createdAt: number;
};

/**
 * Undo/redo or audit log entry types for map edits.
 */
export type HistoryEntryKind =
  | 'add-layer'
  | 'remove-layer'
  | 'style-change'
  | 'draw'
  | 'delete-feature'
  | 'analysis'
  | 'annotation';

/**
 * Single undo/redo history record with optional serialized state delta.
 */
export type HistoryEntry = {
  /** Unique id for this history row (stable across the session). */
  id: string;
  /** Category of change for grouping and localized descriptions. */
  type: HistoryEntryKind;
  /** Human-readable summary shown in the history panel. */
  description: string;
  /** Engine-specific serialized delta or payload to apply/revert the change. */
  data: any;
  /** When the entry was recorded, Unix milliseconds since epoch (UTC). */
  timestamp: number;
};

/**
 * Parameters to run a geoprocessing or analysis job and place its output in the layer tree.
 */
export type AnalysisParams = {
  /** Analysis algorithm key (e.g. buffer, intersect); must match a registered tool. */
  type: string;
  /** Input vector layer id to read features from. */
  inputLayerId: string;
  /** Name for the resulting output layer or group node. */
  outputName: string;
  /** Target `LayerGroup.id` where the output layer should appear. */
  outputGroupId: string;
  /** Tool-specific numeric and boolean options (distances in meters if not noted otherwise). */
  params: Record<string, any>;
  /** When true, show a transient preview layer before committing results. */
  preview: boolean;
};

/**
 * Transient notification shown in the app chrome (status / errors / confirmations).
 */
export type ToastMessage = {
  /** Unique id for deduplication and programmatic dismissal. */
  id: string;
  /** Severity / icon category for styling. */
  type: 'success' | 'warning' | 'error' | 'info';
  /** Short headline for the toast. */
  title: string;
  /** Optional longer explanation or error detail. */
  description?: string;
  /** Optional primary action (e.g. undo): button label and handler. */
  action?: {
    /** Button label text. */
    label: string;
    /** Invoked when the user activates the action; must be side-effect safe for UI. */
    onClick: () => void;
  };
  /** Auto-dismiss duration in milliseconds; default 5000 ms when omitted by the UI layer. */
  duration?: number;
};

/**
 * Authoritative map navigation state (center, zoom, attitude, mode).
 */
export type MapViewState = {
  /** Map center as `[longitude, latitude]` in degrees (WGS84 unless configured otherwise). */
  center: [number, number];
  /** Zoom level; unitless, typically consistent with tile zoom conventions. */
  zoom: number;
  /** Bearing (rotation about vertical) in radians; 0 = north up. */
  bearing: number;
  /** Pitch in radians; 0 = top-down. */
  pitch: number;
  /** Active view mode for UI and camera controller. */
  mode: '2d' | '25d' | 'globe';
};

/**
 * Active map interaction tool (navigation, selection, drawing, measurement).
 */
export type ToolType =
  | 'pan'
  | 'select-click'
  | 'select-box'
  | 'select-lasso'
  | 'draw-point'
  | 'draw-line'
  | 'draw-polygon'
  | 'draw-rect'
  | 'draw-circle'
  | 'draw-freehand'
  | 'measure-distance'
  | 'measure-area'
  | 'measure-profile';

/**
 * Coordinate readout format for the status bar / cursor position.
 */
export type CoordinateFormat = 'dd' | 'dms' | 'utm' | 'mgrs';

/**
 * Keys for analysis tool dialogs opened from the toolbar menu.
 */
export type AnalysisDialogId =
  | 'buffer'
  | 'overlay'
  | 'contour'
  | 'heatmap'
  | 'voronoi'
  | 'viewshed'
  | 'slope'
  | 'hillshade'
  | 'classification';

/**
 * Unit system for distance and area readouts and measure tools.
 */
export type DistanceUnit = 'metric' | 'imperial' | 'nautical';

/**
 * Responsive layout bucket for adaptive UI (toolbar density, panels).
 */
export type Breakpoint = 'desktop' | 'tablet' | 'mobile';

/**
 * Reusable palette definition for thematic styling.
 */
export type StylePreset = {
  /** Unique preset id for persistence and dropdown selection. */
  id: string;
  /** User-visible preset name. */
  name: string;
  /** Ordered color stops as CSS color strings (hex/rgb); length ≥ 2 for ramps. */
  colors: string[];
  /** Palette semantics for UI (legend type and interpolation hints). */
  type: 'categorical' | 'sequential' | 'diverging';
};

/**
 * Result payload from a measurement tool (length, area, or elevation profile).
 */
export type MeasureResult = {
  /** Which measurement class was produced. */
  type: 'distance' | 'area' | 'profile';
  /** Primary numeric result (length, area, or profile distance along path) in `unit` or derived. */
  value: number;
  /** Unit label for `value` (e.g. `"m"`, `"km"`, `"m²"`, `"ft"`). */
  unit: string;
  /** Sampled or vertex coordinates; inner arrays are `[x, y]` or `[lng, lat]` per app CRS. */
  coordinates: number[][];
  /** Optional per-sample elevations in meters (orthometric or ellipsoidal per app setting) for profiles. */
  elevations?: number[];
};

/**
 * Aggregate tile pipeline counters for debug HUD / performance overlay.
 */
export type TileStats = {
  /** Count of tiles that finished loading successfully in the current window or session. */
  loaded: number;
  /** Count of tiles currently in flight (network + decode). */
  loading: number;
  /** Count of tiles resident in CPU/GPU cache and eligible for reuse. */
  cached: number;
  /** Count of tiles that failed after retries (network or decode). */
  errored: number;
};

/**
 * GPU memory attribution snapshot (budget vs usage by resource category).
 */
export type GPUMemoryInfo = {
  /** Estimated total GPU memory currently used by the engine, in bytes. */
  used: number;
  /** Configured or detected memory budget cap for the GPU resource manager, in bytes. */
  budget: number;
  /** Bytes attributed to texture objects (atlas, terrain, attachments). */
  textures: number;
  /** Bytes attributed to buffer objects (geometry, uniforms, staging). */
  buffers: number;
  /** Approximate memory attributed to pipeline objects if tracked; bytes. */
  pipelines: number;
};

/**
 * Legend symbol shape for auto-generated layer legends.
 */
export type LegendShape = 'square' | 'line' | 'circle' | 'gradient';

/**
 * One row in a generated legend (color swatch + label).
 */
export type LegendItemEntry = {
  /** CSS color string for the swatch or gradient key color. */
  color: string;
  /** Human-readable class or range label. */
  label: string;
  /** Visual shape of the legend glyph. */
  shape: LegendShape;
};

/**
 * Aggregated legend rows for one map layer (name + style-derived entries).
 */
export type LegendItem = {
  /** Layer display name from `LayerConfig.name`. */
  layerName: string;
  /** One or more legend rows (single fill, line classes, ramp stops, …). */
  entries: LegendItemEntry[];
};
